#!/usr/bin/env python3
"""kb: the project knowledge base's inline index, lint and stats.

The knowledge-base skill's shipped tool (ADR-0078, issue #625). Pages
live in docs/kb/*.md, each with `summary`, `sources`, `verified` and
`related` frontmatter. `index` writes one line per page, from its
summary (the line's one owner), into every always-loaded file present
(CLAUDE.md, AGENTS.md) between managed markers, idempotently. `lint`
returns label-prefixed problem strings: index over budget, missing
frontmatter, broken sources/related/links, orphans, and stale pages —
a cited source changed in git since the page's verified commit.

  python3 kb.py index [root]   write the inline index
  python3 kb.py lint [root]    check the knowledge base
  python3 kb.py stats [root]   page count, index size, page lengths (JSON)

Root defaults to the working directory, the way the skill invokes it.
Not to be confused with knowledge_plane.py: the knowledge plane is the
run artifacts; the knowledge base is the project's durable non-inferable
facts (CONTEXT.md).
"""
import json
import re
import sys
from pathlib import Path

import cli
from protocol import read_frontmatter

LABEL = "kb"
KB_DIR = Path("docs") / "kb"
TARGETS = ("CLAUDE.md", "AGENTS.md")
# Bytes of the whole managed block, markers included. It is paid on every
# turn of every session, so it is held to the ~2KB the evidence prices
# (docs/research/knowledge-base-evidence.md, change 1).
INDEX_BUDGET = 2048
FIELDS = ("summary", "sources", "verified", "related")
# related may be empty; the others must say something.
OPTIONAL_VALUE = ("related",)
BEGIN = ("<!-- BEGIN KB INDEX: generated by kb.py index;"
         " edit page summaries, not this block -->")
END = "<!-- END KB INDEX -->"
BLOCK = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.S)
ENTRY = re.compile(r"^- (docs/kb/[^:\s]+\.md):", re.M)
LOCAL_LINK = re.compile(r"\]\(([^)#][^)]*)\)")
NO_KB = (f"{LABEL}: no docs/kb/ directory — the knowledge-base skill's"
         " setup flow creates it")


def _items(value):
    """A frontmatter list — `a, b` or `[a, b]` — as its non-empty items."""
    return [item.strip() for item in value.strip().strip("[]").split(",")
            if item.strip()]


def pages(root):
    """Every page under docs/kb/, sorted by slug: {slug, path (repo
    relative, posix), file (Path), fields (dict, or None without a
    frontmatter block)}."""
    root = Path(root)
    return [{"slug": path.stem,
             "path": path.relative_to(root).as_posix(),
             "file": path,
             "fields": read_frontmatter(path)}
            for path in sorted((root / KB_DIR).glob("*.md"))]


def render_index(pages):
    """The managed block, markers included, for the pages that carry a
    summary — the one place an index line comes from."""
    lines = [f"- {p['path']}: {p['fields']['summary']}" for p in pages
             if (p["fields"] or {}).get("summary")]
    body = "\n".join(lines) if lines else "(no pages yet)"
    return (f"{BEGIN}\n## Knowledge base\n\n"
            "Non-inferable project knowledge, one page per line. Read a"
            " page before changing what its line names.\n\n"
            f"{body}\n{END}")


def targets(root):
    """The always-loaded files present at root, a symlinked twin once."""
    seen, found = set(), []
    for name in TARGETS:
        path = Path(root) / name
        if path.is_file() and path.resolve() not in seen:
            seen.add(path.resolve())
            found.append(path)
    return found


def _budget_problems(block):
    size = len(block.encode("utf-8"))
    if size <= INDEX_BUDGET:
        return []
    return [f"{LABEL}: the index is {size} bytes, over its {INDEX_BUDGET}"
            "-byte budget — shorten summaries or merge pages"]


def _field_problems(page):
    if page["fields"] is None:
        return [f"{LABEL}: {page['path']} has no frontmatter block"]
    return [f"{LABEL}: {page['path']} is missing frontmatter field"
            f" {field!r}" for field in FIELDS
            if field not in page["fields"]
            or (not page["fields"][field] and field not in OPTIONAL_VALUE)]


def _write(path, block):
    text = path.read_text(encoding="utf-8")
    if BLOCK.search(text):
        new = BLOCK.sub(lambda _: block, text, count=1)
    else:
        new = text.rstrip("\n") + "\n\n" + block + "\n"
    if new != text:
        path.write_text(new, encoding="utf-8")


def index(root):
    """Write the inline index into every always-loaded file; problems
    instead when there is nothing to write into, a page has no summary,
    or the block would break its budget — nothing is written then."""
    root = Path(root)
    if not (root / KB_DIR).is_dir():
        return [NO_KB]
    found = targets(root)
    if not found:
        return [f"{LABEL}: neither CLAUDE.md nor AGENTS.md exists to hold"
                " the index"]
    every = pages(root)
    block = render_index(every)
    problems = [_field_problems(page)[0] for page in every
                if not (page["fields"] or {}).get("summary")]
    problems += _budget_problems(block)
    if problems:
        return problems
    for path in found:
        _write(path, block)
    return []


def _link_problems(root, page):
    fields, label = page["fields"], f"{LABEL}: {page['path']}"
    slugs = {p.stem for p in (root / KB_DIR).glob("*.md")}
    problems = [f"{label} cites source {source!r}, which does not exist"
                for source in _items(fields.get("sources", ""))
                if not (root / source).exists()]
    problems += [f"{label} relates to {slug!r}, which is not a page in"
                 " docs/kb/" for slug in _items(fields.get("related", ""))
                 if slug not in slugs]
    text = page["file"].read_text(encoding="utf-8")
    problems += [f"{label} links to {ref!r}, which does not exist"
                 for ref in LOCAL_LINK.findall(text)
                 if "://" not in ref
                 and not (page["file"].parent / ref.split("#")[0]).exists()]
    return problems


def _index_problems(path, every, block):
    name = path.name
    match = BLOCK.search(path.read_text(encoding="utf-8"))
    if not match:
        return [f"{LABEL}: {name} has no knowledge-base index — run kb.py"
                " index"]
    listed = set(ENTRY.findall(match.group(0)))
    present = {p["path"] for p in every}
    problems = [f"{LABEL}: {p['path']} is an orphan: the index in {name}"
                " does not list it — run kb.py index"
                for p in every if p["path"] not in listed]
    problems += [f"{LABEL}: the index in {name} lists {entry}, which does"
                 " not exist" for entry in sorted(listed - present)]
    if not problems and match.group(0) != block:
        problems.append(f"{LABEL}: the index in {name} is out of date with"
                        " the page summaries — run kb.py index")
    return problems


def _stale_problems(root, page, git):
    """A page is stale once a source it cites changed between its
    verified commit and HEAD. Raises cli.CLI_FAILURES only for git
    itself; an unknown sha is the page's problem."""
    fields, label = page["fields"], f"{LABEL}: {page['path']}"
    sha, sources = fields.get("verified", ""), _items(
        fields.get("sources", ""))
    if not sha or not sources:
        return []
    base = ["-C", str(root)]
    try:
        git(base + ["rev-parse", "--verify", "--quiet", f"{sha}^{{commit}}"])
    except cli.CLI_FAILURES as err:
        if isinstance(err, OSError):
            raise
        return [f"{label} verified {sha!r} is not a commit in this"
                " repository"]
    changed = git(base + ["diff", "--name-only", sha, "HEAD", "--",
                          *sources]).split()
    if not changed:
        return []
    return [f"{label} is stale: {', '.join(changed)} changed since"
            f" verified {sha[:7]} — re-verify it"]


def _git(args):
    return cli.runner("git")(args).stdout


def lint(root, git=_git):
    """Every problem with the knowledge base at root, as problem strings."""
    root = Path(root)
    if not (root / KB_DIR).is_dir():
        return [NO_KB]
    every = pages(root)
    block = render_index(every)
    problems = _budget_problems(block)
    for page in every:
        problems += _field_problems(page)
    for page in every:
        if page["fields"] is not None:
            problems += _link_problems(root, page)
    found = targets(root)
    if not found:
        problems.append(f"{LABEL}: neither CLAUDE.md nor AGENTS.md exists"
                        " to hold the index")
    for path in found:
        problems += _index_problems(path, every, block)
    try:
        for page in every:
            if page["fields"] is not None:
                problems += _stale_problems(root, page, git)
    except cli.CLI_FAILURES as err:
        problems.append(f"{LABEL}: git is unavailable: {cli.detail(err)}")
    return problems


def stats(root):
    """(stats dict, problems): page count, index size against its budget,
    and each page's length in lines."""
    root = Path(root)
    if not (root / KB_DIR).is_dir():
        return None, [NO_KB]
    every = pages(root)
    return {"pages": len(every),
            "index_bytes": len(render_index(every).encode("utf-8")),
            "index_budget": INDEX_BUDGET,
            "page_lines": {p["slug"]: len(p["file"].read_text(
                encoding="utf-8").splitlines()) for p in every}}, []


USAGE = "usage: kb.py index|lint|stats [root]"


def main(argv):
    """`python3 kb.py <index|lint|stats> [root]`."""
    if not argv or argv[0] not in ("index", "lint", "stats") or len(argv) > 2:
        print(USAGE)
        return 2
    verb, root = argv[0], argv[1] if len(argv) > 1 else "."
    if verb == "stats":
        result, problems = stats(root)
        if problems:
            return cli.report(LABEL, problems)
        print(json.dumps(result, indent=2))
        return 0
    return cli.report(LABEL, index(root) if verb == "index" else lint(root))


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
